- name: JQ is present
  apt:
    name: jq
    force: yes
  tags: [common]

- name: Hosts file is present and has appropriate entries
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.host_ip }}"
    line: "{{ item.host_ip }} {{ item.host_name }}"
  with_items: "{{ hosts }}"
  tags: [common]

- name: Services are not running
  service:
    name: "{{ item }}"
    state: stopped
  ignore_errors: yes
  with_items: "{{ obsolete_services }}"
  tags: [common]
