- hosts: swarm
  remote_user: ubuntu
  serial: 1
  vars:
    - debian_version: wily
    - docker_cfg_dest: /lib/systemd/system/docker.service
    - is_systemd: true
    - docker_extra: --log-driver=syslog --log-opt syslog-address=tcp://{{ logging_ip }}:25826 --log-opt tag={{ '{{.Name}}' }}
  roles:
    - common
    - rsyslog
    - docker
    - consul
    - swarm
    - registrator
